docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

prerequisite_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg-agent

docker_repo_url: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_gpg_key: https://download.docker.com/linux/ubuntu/gpg