- name: Install PHP and extensions
  package:
    name: ['php', 'libapache2-mod-php', 'php-mysql'] 
    state: present

- name: Restart Apache to load PHP module
  service:
    name: apache2
    state: restarted