- name: Ensure Docker is running and enabled
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  tags: docker
  notify: Reload user groups