- name: Ensure firewalld is running
  hosts: localhost 
  tasks:
    - name: Check if firewalld is installed
      package:
          name: firewalld
          state: present
    - name: Enable and start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
      when: (ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution_major_version'] >= '7') or (ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] >= '8')