services:
  web:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/app_db
      - REDIS_URL=redis://cache:6379
    ports:
      - "8000:8000"
    networks:
      - backend

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  cache:
    image: redis:7-alpine
    container_name: redis_cache
    networks:
      - backend

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
